export const LPOMoviments = [
 "Back Squat",
 "Bench Press",
 "Clean",
 "CLean & Jerk",
 "Clean Pull",
 "Cluster",
 "Deadlift",
 "Deadlift Fat Bar",
 "Floor Press",
 "Front Squat",
 "Hang Clean",
 "Hang Power Clean",
 "Hang Power Snatch",
 "Hang Snatch",
 "Muscle Clean",
 "Muscle Snatch",
 "Overhead Lunge",
 "Overhead Squat",
 "Power Clean",
 "Power Snatch",
 "Push Jerk",
 "Push Press",
 "Shoulder Press",
 "Snatch",
 "Snatch Balance",
 "Snatch Deadlift",
 "Snatch Pull",
 "Split Jerk",
 "Squat Clean",
 "Squat Jerk",
 "Squat Snatch",
 "Sumo Deadlift",
 "Sumo Deadlift High Pull",
 "Thruster",



]