export const GymnasticMoviments = [
 {moviment: "Abmat Sit-up Max Reps", record: 0},
 {moviment: "Box Jump Max Height", record: 0},
 {moviment: "DU Max Reps", record: 0},
 {moviment: "HSPU Max Reps", record: 0},
 {moviment: "Handstand Walk max distance", record: 0},
 {moviment: "L-sit Max Hold", record: 0},
 {moviment: "MU - 30 Reps for time", record: 0},
 {moviment: "MU Max Reps", record: 0},
 {moviment: "Pull Up chest to bar Max Reps", record: 0},
 {moviment: "Pull Up strict Max Reps", record: 0},
 {moviment: "Pull Up Weighted 1 Rep Mx", record: 0},
 {moviment: "Push Up Max Reps", record: 0},
 {moviment: "Ring Dip Max Reps", record: 0},
 {moviment: "Rope Climp Wrapping", record: 0},
 {moviment: "Seated Leg Raises", record: 0},
 {moviment: "Skin the Cat", record: 0},
 {moviment: "Tabata Squat", record: 0},
 {moviment: "Toes To Bar Max Reps", record: 0},
 {moviment: "Wall Ball Max Reps", record: 0}
]