export const LPOMoviments = [
 {moviment: "Back Squat", record: 0},
 {moviment: "Bench Press", record: 0},
 {moviment: "Clean", record: 0},
 {moviment: "Clean & Jerk", record: 0},
 {moviment: "Clean Pull", record: 0},
 {moviment: "Cluster", record: 0},
 {moviment: "Deadlift", record: 0},
 {moviment: "Deadlift Fat Bar", record: 0},
 {moviment: "Floor Press", record: 0},
 {moviment: "Front Squat" , record: 0},
 {moviment: "Hang Clean", record: 0},
 {moviment: "Hang Power Clean" , record: 0},
 {moviment: "Hang Power Snatch", record: 0},
 {moviment: "Muscle Clean", record: 0},
 {moviment: "Muscle Snatch", record: 0},
 {moviment: "Overhead Lunge", record: 0},
 {moviment: "Overhead Squat", record: 0},
 {moviment: "Power Clean", record: 0},
 {moviment: "Power Snatch", record: 0},
 {moviment: "Push Jerk", record: 0},
 {moviment: "Push Press", record: 0},
 {moviment: "Shoulder Press", record: 0},
 {moviment: "Snatch", record: 0},
 {moviment: "Snatch Balance", record: 0},
 {moviment: "Snatch Deadlift", record: 0},
 {moviment: "Snatch Pull", record: 0},
 {moviment: "Split Jerk", record: 0},
 {moviment: "Squat Clean", record: 0},
 {moviment: "Squat Jerk", record: 0},
 {moviment: "Squat Snatch", record: 0},
 {moviment: "Sumo Deadlift", record: 0},
 {moviment: "Sumo Deadlift High Pull", record: 0},
 {moviment: "Thruster", record: 0}
]